### ISSUE TITLE
可以上传一下数据库sql文件吗

### ISSUE THREAD

**Issue by honghaishui** [jianglin-0425/MyRead#1]

**Comment by jianglin-0425** [comment]
sql文件太大了，全是爬书籍章节600M大小，就没有上传发自我的手机-------- 原始邮件 --------发件人： honghaishui ***@***.***>日期： 2022年2月25日周五 中午11:15收件人： jianglin-0425/MyRead ***@***.***>抄送： Subscribed ***@***.***>主    题： [jianglin-0425/MyRead] 可以上传一下数据库sql文件吗 (Issue #1)

**Comment by honghaishui** [comment]
可以用网盘分享一下不，因为没有sql文件程序跑不起来，辛苦大佬

**Comment by jianglin-0425** [comment]
额，我是个学生


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianglin-0425/MyRead"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jianglin-0425/MyRead] 可以上传一下数据库sql文件吗 (Issue #1)





 
可以用网盘分享一下不，因为没有sql文件程序跑不起来，辛苦大佬
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jianglin-0425** [comment]
重新下载一下代码
jianglin-0425/WebRead: 在线书城，仿照笔趣阁，ssm架构，Java语言 数据库MySQL 开发工具：idea (github.com)
SQL文件：
链接：https://pan.baidu.com/s/15lsH7TXc-1bybGoJjqejHQ&nbsp;
提取码：7530

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jianglin-0425/MyRead"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 中午11:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jianglin-0425/MyRead] 可以上传一下数据库sql文件吗 (Issue #1)





 
可以用网盘分享一下不，因为没有sql文件程序跑不起来，辛苦大佬
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by honghaishui** [comment]
多谢
